version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/Basabi-lab/lms

    steps:
      - checkout

      - run: sudo apt-get update
      - run: sudo apt-get install -y libtag1-dev libtagc0-dev
      - run:
          name: setting sample song timestamp
          command: |
            sh /go/src/github.com/Basabi-lab/lms/tests/set_timestamp_song.sh

      - run: go get -v -t -d ./...
      - run: go test -v ./...
