version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/Basabi-lab/lms

    steps:
      - checkout

      - run: apt update
      - run: apt install libtag1-dev

      - run: go get -v -t -d ./...
      - run: go test -v ./...
