version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/Basabi-lab/lms

    steps:
      - checkout

      - run: sudo apt-get update
      - run: sudo apt-get install -y libtag1-dev libtagc0-dev

      - run: go get -v -t -d ./...
      - run: go test -v ./...

      - run: go get github.com/mattn/goveralls
      - run: goveralls -v -service=circle-ci -repotoken $COVERALLS_TOKEN ./lms
      - run: goveralls -v -service=circle-ci -coverprofile=/go/src/$PROJECT_GO_PACKAGE/coverage.out -repotoken $COVERALLS_TOKEN ./lms
