version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/Basabi-lab/lms

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test ./... -v -covermode=count -coverprofile=coverage.out
      - run: go build

      - run: go get github.com/mattn/goveralls
      - run: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN
